name: ActionBarTimer
version: SNAPSHOT
author: jonthesquirrel
main: io.github.jonthesquirrel.actionbartimer.Main
website: https://github.com/jonthesquirrel/ActionBarTimer
depend: [ActionBarAPI]
commands:
  timer:
    description: Control the action bar timer
    usage: /timer <set [[hh:]mm:]ss|clear|pause|unpause|add|remove>
    permission: actionbartimer.use